module.exports = {
  appName: 'Modrinth',
  navLinks: [
    { label: 'Overview', path: 'dashboard', icon: 'dashboard' },
    { label: 'Projects', path: 'dashboard/projects', icon: 'list' },
    {
      label: 'Analytics',
      path: 'dashboard/analytics',
      icon: 'chart',
      condition: 'analytics',
    },
    {
      label: 'Revenue',
      path: 'dashboard/revenue',
      icon: 'currency',
      condition: 'monetization',
    },
  ],
  revenue: {
    processingFees:
      'To avoid paying unnecessary fee deductions, you may want to wait to transfer your money out after it accumulates for a bit rather than transferring as soon as you reach the minimum of $',
    deduction1: 'Modrinth will deduct ',
    deductionAmount: '2%',
    deduction2: 'for the fee (minimum of $0.25 and maximum of $20) from ',
    deduction2Strong: 'all transfers',
    deduction3:
      ' and if the fee PayPal charges is less than the amount we deducted, the difference will be added back to your Modrinth balance. This happens as Modrinth cannot determine if a transaction will be in the United States or international or not until after the transaction has been made.',
    currencyConversion:
      'All revenue generated by Modrinth is in United States dollars. Any conversions to your local currency will happen at withdrawal and is not handled by Modrinth. Modrinth cannot guarantee any exchange rate, so only USD is displayed in the creator dashboard.',
  },
}
