export const DEV_URL = 'http://localhost:3000'
export const STAGING_URL = 'https://staging.modrinth.com'
export const STAGING_API_URL = 'https://staging-api.modrinth.com/v2/'
export const STAGING_ARIADNE_URL = 'https://staging-ariadne.modrinth.com/v1/'
export const PRODUCTION_URL = 'https://modrinth.com'
